languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "快乐星球"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.png"
  description = "DeFi 爱好者，喜欢钻研投资和空投策略，乐于分享有价值的见解和经验！"

[params.author]
  name = "BitHappy"
  image = "img/author.png"
  headline = "DeFi 爱好者，喜欢钻研投资和空投策略，乐于分享有价值的见解和经验！"
  bio = "DeFi 爱好者，喜欢钻研投资和空投策略，乐于分享有价值的见解和经验！"
  links = [
    { x-twitter = "https://x.com/BitHappyX" },
    { telegram = "https:/t.me/BitHappyX" },
    { github = "https://github.com/BitHappyX" },
    { email = "mailto:BitHappyX@outlook.com" },
    { youtube = "https://www.youtube.com/@BitHappyX" },
  ]