# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Web3 常用网站"
  pageRef = "navigation"
  weight = 1
  
[[main]]
  name = "DeFi 计算器"
  pageRef = "defi-calc"
  weight = 2

[[main]]
  name = "哈皮杂谈"
  pageRef = "happy-talk"
  weight = 10

[[main]]
  name = "投研报告"
  pageRef = "research"
  weight = 20

[[main]]
  name = "教程"
  weight = 30

[[main]]
  name = "新手教程"
  parent = "教程"
  pageRef = "tutorials/beginner"
  weight = 31

[[main]]
  name = "空投教程"
  parent = "教程"
  pageRef = "tutorials/airdrops"
  weight = 32

[[main]]
  name = "赚钱小技巧"
  parent = "教程"
  pageRef = "tutorials/rich"
  weight = 33

#[[main]]
#  name = "周边"
#  url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
#  weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/BitHappyX"
  weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/BitHappyX"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "标签"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "作者"
#   pageRef = "authors"
#   weight = 20
